### ISSUE TITLE
Failing to send reminders after a restart

### ISSUE THREAD

**Issue by x2brainsx** [acocalypso/DiscordRoleManager#5]
Hi

I have DiscordRoleManager running with PM2 as it will lose connecton every so often and stop running (or if i get the syntax wrong). The problem I find is it forgets to send out reminders and remove members without manual intervention. 

If I issue a !temprole check againsts my members it then notices how long left is on the membership and reminds/removes as needed. Would it be possible for it to essentially "!temprole check" all members in the database each time it starts?

Thanks

**Comment by acocalypso** [comment]
Can you Check which Error Messages appears? You May also enable Debugging in config

**Comment by acocalypso** [comment]
@x2brainsx please git pull and check if its working again

**Comment by x2brainsx** [comment]
Thanks for the update, For reference the errors in my logs before updating were almost all Error 4000, but with a couple others as below

{ Error: 4000: Unknown error.
    at Shard._onWSClose (/home/brains/DiscordRoleManager/node_modules/eris/lib/gateway/Shard.js:1855:23)
    at WebSocket.emit (events.js:198:13)
    at WebSocket.emitClose (/home/brains/DiscordRoleManager/node_modules/ws/lib/websocket.js:191:10)
    at TLSSocket.socketOnClose (/home/brains/DiscordRoleManager/node_modules/ws/lib/websocket.js:858:15)
    at TLSSocket.emit (events.js:203:15)
    at _handle.close (net.js:607:12)
    at TCP.done (_tls_wrap.js:388:7) code: 4000 }

{ Error: Connection reset by peer
    at Shard._onWSClose (/home/brains/DiscordRoleManager/node_modules/eris/lib/gateway/Shard.js:1853:23)
    at WebSocket.emit (events.js:198:13)
    at WebSocket.emitClose (/home/brains/DiscordRoleManager/node_modules/ws/lib/websocket.js:191:10)
    at TLSSocket.socketOnClose (/home/brains/DiscordRoleManager/node_modules/ws/lib/websocket.js:858:15)
    at TLSSocket.emit (events.js:203:15)
    at _handle.close (net.js:607:12)
    at TCP.done (_tls_wrap.js:388:7) code: 1006 }

{ Error: 1001: 
    at Shard._onWSClose (/home/brains/DiscordRoleManager/node_modules/eris/lib/gateway/Shard.js:1810:51)
    at WebSocket.emit (events.js:198:13)
    at WebSocket.emitClose (/home/brains/DiscordRoleManager/node_modules/ws/lib/websocket.js:191:10)
    at TLSSocket.socketOnClose (/home/brains/DiscordRoleManager/node_modules/ws/lib/websocket.js:858:15)
    at TLSSocket.emit (events.js:203:15)
    at _handle.close (net.js:607:12)
    at TCP.done (_tls_wrap.js:388:7) code: 1001 }

The git pull overwrote my database with the one from the Repo :-/ so have added all my members back in with Debug on and will update in a few days once I know if it is working correctly or not.

**Comment by acocalypso** [comment]
does the issue still exists on your site?

**Comment by x2brainsx** [comment]
Afraid so, Example of my test account that should have lost its role 4 days ago. Manually issuing a check woke it up and removed the account, but i would have to do the same for each and every account if their time was up.

![image](https://user-images.githubusercontent.com/80002130/111069513-479fa280-84c5-11eb-8fd1-b7e3564f0de7.png)

Since the update I initially had a couple logs entries for error 1006, but after that it has just been showing "Ready!" and "Table created"

{ Error: Connection reset by peer
    at Shard._onWSClose (/home/brains/DiscordRoleManager/node_modules/eris/lib/gateway/Shard.js:2086:23)
    at WebSocket.emit (events.js:198:13)
    at WebSocket.emitClose (/home/brains/DiscordRoleManager/node_modules/ws/lib/websocket.js:198:10)
    at TLSSocket.socketOnClose (/home/brains/DiscordRoleManager/node_modules/ws/lib/websocket.js:886:15)
    at TLSSocket.emit (events.js:203:15)
    at _handle.close (net.js:607:12)
    at TCP.done (_tls_wrap.js:388:7) code: 1006 }

![image](https://user-images.githubusercontent.com/80002130/111070025-b3830a80-84c7-11eb-9bf6-ed20bdd9bc7e.png)

**Comment by acocalypso** [comment]
After investigating that issue I found out that Discord is cancelling the connections from time to time.
code: 1006 - reset by peer

There is nothing I can do about.

The only strange thing is that the bot only deletes the user after you executed a command.

Never had that issue on my site.

You can ignore the Table created messages, those reappear every restart of the bot.

**Comment by x2brainsx** [comment]
Thanks for taking a look, I realise you shouldn't need to do this, but any chance of a loop that runs the check command over all users in the database when the bot starts? maybe this loop could be toggled on/off via the config if you don't want it to be a always on thing. That would esentially do what I have todo manually to get the bot to wake up.

If not, then I will try moving the bot off my VPS to somewhere else to see if that helps.

**Comment by acocalypso** [comment]
There is already a loop which is checking for expired accounts and removes them from the db

https://github.com/acocalypso/DiscordRoleManager/blob/35e5d1ee41872c2c8a45ec1221b50454aec18243/start.js#L28

which runs every 1 min
https://github.com/acocalypso/DiscordRoleManager/blob/35e5d1ee41872c2c8a45ec1221b50454aec18243/start.js#L115

**Comment by x2brainsx** [comment]
ok no worries, my coding skills are minimal, hence asking the question. I'll setup a new install on a different machine and see what happens
